// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "RSO_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RSOFast_arma
Rcpp::List RSOFast_arma(const arma::mat& x, const arma::vec& y, double tau, const arma::vec& penalty_factor, Rcpp::Nullable<Rcpp::NumericVector> gaminitNV);
RcppExport SEXP _RSO_RSOFast_arma(SEXP xSEXP, SEXP ySEXP, SEXP tauSEXP, SEXP penalty_factorSEXP, SEXP gaminitNVSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type penalty_factor(penalty_factorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type gaminitNV(gaminitNVSEXP);
    rcpp_result_gen = Rcpp::wrap(RSOFast_arma(x, y, tau, penalty_factor, gaminitNV));
    return rcpp_result_gen;
END_RCPP
}
// ridgereg_fast_arma
double ridgereg_fast_arma(const arma::mat& x, const arma::vec& y, const arma::vec& gam, const arma::vec& penalty_factor);
RcppExport SEXP _RSO_ridgereg_fast_arma(SEXP xSEXP, SEXP ySEXP, SEXP gamSEXP, SEXP penalty_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type penalty_factor(penalty_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(ridgereg_fast_arma(x, y, gam, penalty_factor));
    return rcpp_result_gen;
END_RCPP
}
// ridgeRegPrecomp_arma
double ridgeRegPrecomp_arma(const arma::mat& x, const arma::vec& y, const arma::vec& gam, const arma::vec& penalty_factor, const Rcpp::List& precomp);
RcppExport SEXP _RSO_ridgeRegPrecomp_arma(SEXP xSEXP, SEXP ySEXP, SEXP gamSEXP, SEXP penalty_factorSEXP, SEXP precompSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type penalty_factor(penalty_factorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type precomp(precompSEXP);
    rcpp_result_gen = Rcpp::wrap(ridgeRegPrecomp_arma(x, y, gam, penalty_factor, precomp));
    return rcpp_result_gen;
END_RCPP
}
// ridgeregWdf_fast_arma
Rcpp::List ridgeregWdf_fast_arma(const arma::mat& x, const arma::vec& y, const arma::vec& gam, const arma::vec& penalty_factor);
RcppExport SEXP _RSO_ridgeregWdf_fast_arma(SEXP xSEXP, SEXP ySEXP, SEXP gamSEXP, SEXP penalty_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gam(gamSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type penalty_factor(penalty_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(ridgeregWdf_fast_arma(x, y, gam, penalty_factor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSO_RSOFast_arma", (DL_FUNC) &_RSO_RSOFast_arma, 5},
    {"_RSO_ridgereg_fast_arma", (DL_FUNC) &_RSO_ridgereg_fast_arma, 4},
    {"_RSO_ridgeRegPrecomp_arma", (DL_FUNC) &_RSO_ridgeRegPrecomp_arma, 5},
    {"_RSO_ridgeregWdf_fast_arma", (DL_FUNC) &_RSO_ridgeregWdf_fast_arma, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
