# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RSOFast_arma <- function(x, y, tau, penalty_factor, gaminitNV = NULL) {
    .Call(`_RSO_RSOFast_arma`, x, y, tau, penalty_factor, gaminitNV)
}

ridgereg_fast_arma <- function(x, y, gam, penalty_factor) {
    .Call(`_RSO_ridgereg_fast_arma`, x, y, gam, penalty_factor)
}

ridgeRegPrecomp_arma <- function(x, y, gam, penalty_factor, precomp) {
    .Call(`_RSO_ridgeRegPrecomp_arma`, x, y, gam, penalty_factor, precomp)
}

ridgeregWdf_fast_arma <- function(x, y, gam, penalty_factor) {
    .Call(`_RSO_ridgeregWdf_fast_arma`, x, y, gam, penalty_factor)
}

